---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: nextcloud-db
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: "nextcloud"
            - name: PMA_PASSWORD
              value: "nextcloudpassword"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: nextcloud
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
